name: generate

permissions:
  contents: write

on:
  push:
    branches: ["main"]
    paths-ignore:
      - 'README.md'
  schedule:
    - cron:  '30 12 * * *'

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt;
      - name: generate README
        run: python -u db-monthly.py
      - name: push README
        run: |
          if [[ -z $(git status README.md -s) ]]
          then
            echo "no changed"
          else
            echo "README changed, so commit it"
            git config user.name github-actions
            git config user.email github-actions@github.com
            git commit -am "Automated generated"+(date +%Y%m%d)
            git push
            exit
          fi
          shell: bash
